account/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', Login.as_view()),
    path('logout/', Logout.as_view()),
    path('signup/', SignUpView.as_view()),
    path('', AccountUpdateView.as_view()),
    path('profile/', ProfileUpdateView.as_view()),
    path('password_reset/', PasswordReset.as_view()), # Django 4.0でメール送信エラー確認。4.2.7にアップデートで解消
    path('password_reset_done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from base import views
import os

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('account.urls')),
    
    path('', views.IndexListView.as_view()),
    path('items/<str:pk>/', views.ItemDetailView.as_view()),
    path('categories/<str:pk>/', views.CategoryListView.as_view()),
    path('tags/<str:pk>/', views.TagListView.as_view()),

    path('cart/', views.CartListView.as_view()),
    path('cart/add/', views.AddCartView.as_view()),
    path('cart/remove/<str:pk>/', views.remove_from_cart),

    path('pay/checkout/', views.PayWithStripe.as_view()),
    path('pay/success/', views.PaySuccessView.as_view()),
    path('pay/cancel/', views.PayCancelView.as_view()),

    path('orders/', views.OrderIndexView.as_view()),
    path('orders/<str:pk>/', views.OrderDetailView.as_view()),

    path('downloads/capture/<str:id>/', views.Download.as_view()),

    path('about_us/', views.AboutUsView.as_view()),
    path('legal_information/', views.LegalInformationView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=os.path.join(settings.MEDIA_ROOT, 'media'))

    

account/models.py
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from base.models import create_id
 
 
class UserManager(BaseUserManager):
 
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username = username,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
 
 
class User(AbstractBaseUser):
    id = models.CharField(default=create_id, primary_key=True, max_length=32)
    username = models.CharField(
        max_length=50, blank=True, default='Anonymous')
    email = models.EmailField(max_length=255, unique=True)
    newsletter = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'username'
    REQUIRED_FIELDS = ['username',]
 
    def __str__(self):
        return self.email
 
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
 
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @classmethod
    def get_email_field_name(cls):
        try:
            return cls.USERNAME_FIELD
        except AttributeError:
            return "email"
        
    @classmethod
    def get_username_field_name(cls):
        try:
            return cls.EMAIL_FIELD
        except AttributeError:
            return "username"
 
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
 
 
class Profile(models.Model):
    user = models.OneToOneField(
        User, primary_key=True, on_delete=models.CASCADE)
    name = models.CharField(default='', blank=True, max_length=50)
    zipcode = models.CharField(default='', blank=True, max_length=8)
    prefecture = models.CharField(default='', blank=True, max_length=50)
    city = models.CharField(default='', blank=True, max_length=50)
    address1 = models.CharField(default='', blank=True, max_length=50)
    address2 = models.CharField(default='', blank=True, max_length=50)
    tel = models.CharField(default='', blank=True, max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
 
    def __str__(self):
        return self.name
 
 
# OneToOneFieldを同時に作成
@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])

account/forms.py
from django import forms
from django.contrib.auth import get_user_model

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()
 
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password', 'newsletter',)
 
    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password
 
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

account/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
                                      PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model, hashers
from django.urls import reverse_lazy
from config import settings
from .models import Profile
from .forms import UserCreationForm
from django.contrib import messages
from .models import User
from django.contrib.auth.forms import PasswordResetForm

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = '/account/login/'
    template_name = 'pages/signup.html'

    def form_valid(self, form):
        messages.success(self.request, 'Sucessed user creation')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Invalid signup information')
        return super().form_invalid(form)
    
class Login(LoginView):
    template_name = 'pages/login.html'

    def form_valid(self, form):
        messages.success(self.request, 'Login successed')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Invalid login information')
        return super().form_invalid(form)
    
class Logout(LogoutView):
    template_name = 'pages/login.html'

    def form_valid(self, form):
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return super().form_invalid(form)
    
class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'pages/account.html'
    fields = ('username', 'email', 'newsletter',)
    success_url = '/account/'

    def get_object(self):
        self.kwargs['pk'] = self.request.user.pk
        return super().get_object()
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('password'):
            user = User.objects.get(pk=request.user.pk)
            valid = True
            if not user.check_password(request.POST.get('current_password')):
                valid = False
                messages.error(request, 'Current password is wrong')

            if request.POST.get('password') != request.POST.get('password_confirm'):
                valid = False
                messages.error(request, 'Mismatch new password and confirmation')

            if not valid:
                return redirect('/account/')
        
            user.password = hashers.make_password(request.POST.get('password'))
            user.save()
            
        return super().post(request, *args, **kwargs)
    
    
    def form_valid(self, form):
        messages.success(self.request, 'Updated')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,'Error')
        return super().form_invalid(form)
    
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'pages/profile.html'
    fields = ('name', 'zipcode', 'prefecture',
              'city', 'address1', 'address2', 'tel')
    success_url = '/profile/'

    def get_object(self):
        self.kwargs['pk'] = self.request.user.pk
        return super().get_object()
    
    def form_valid(self, form):
        messages.success(self.request, 'Updated')
        return super().form_valid(form)
    

class PasswordReset(PasswordResetView):
    email_template_name = "pages/registration/password_reset_email.html"
    extra_email_context = None
    form_class = PasswordResetForm
    from_email = settings.TITLE
    html_email_template_name = None
    subject_template_name = "pages/registration/password_reset_subject.txt"
    success_url = reverse_lazy('password_reset_done')
    template_name = "pages/registration/password_reset_form.html"
    #title = _("Password reset")
    #token_generator = default_token_generator

    def form_valid(self, form):
        return super().form_valid(form)

class PasswordResetDone(PasswordResetDoneView):
    template_name = 'pages/registration/password_reset_done.html'

class PasswordResetConfirm(PasswordResetConfirmView):
    template_name = 'pages/registration/password_reset_confirm.html'
    
    def form_valid(self, form):
        messages.success(self.request, 'Password reset successed')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Error')
        return super().form_invalid(form)
    
class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'pages/registration/password_reset_complete.html'

base/views/about_us_views.py
from django.views.generic import TemplateView

class AboutUsView(TemplateView):
    template_name = 'pages/about_us.html'

base/views/cart_views.py
from django.shortcuts import redirect
from django.conf import settings
from django.views.generic import View, ListView
from base.models import Item
from collections import OrderedDict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
 
class CartListView(LoginRequiredMixin, ListView):
    model = Item
    template_name = 'pages/cart.html'

    def get_queryset(self):
        cart = self.request.session.get('cart', None)
        if cart is None or len(cart) == 0:
            return redirect('/')
        
        self.queryset = []
        self.total = 0

        for item_pk, formats in cart['items'].items():
            obj = Item.objects.get(pk=item_pk)
            obj.quantity = 1
            obj.purchase_formats = formats
            obj.subtotal = int(obj.price * len(formats))
            self.queryset.append(obj)
            self.total += obj.subtotal

        self.tax_included_total = int(self.total * (settings.TAX_RATE + 1))
        cart['total'] = self.total
        cart['tax_included_total'] = self.tax_included_total
        self.request.session['cart'] = cart
        
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context['total'] = self.total
            context['tax_included_total'] = self.tax_included_total
        except Exception:
            pass

        return context

class AddCartView(View):
    def post(self, request):
        item_pk = request.POST.get('item_pk')
        formats = request.POST.getlist('formats')
        if not formats:
            messages.error(request, 'Not select formats')
            return redirect(f'/items/{item_pk}/')

        cart = request.session.get('cart', None)

        if cart is None or len(cart) == 0:
            items = OrderedDict()
            cart = {'items': items}

        cart['items'][item_pk] = formats

        request.session['cart'] = cart

        return redirect('/cart/')

@login_required
def remove_from_cart(request, pk):
    cart = request.session.get('cart', None)
    if cart is not None:
        del cart['items'][pk]
        request.session['cart'] = cart
    
    return redirect('/cart/')

base/views/item_views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from base.models import Item, Order, Category, Capture, Tag
import json

class IndexListView(ListView):
    model = Item
    template_name = 'pages/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all().order_by('order')
        category_dict_list = []
        for category_obj in categories:
            items = Item.objects.filter(category=category_obj.pk, is_published=True).order_by('-created_at')
            dic = {category_obj:items}
            category_dict_list.append(dic)
        context['dict_list'] = category_dict_list
        return context



class ItemDetailView(DetailView):
    model = Item
    template_name = 'pages/item.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = self.get_object()

        # 購入済フォーマットをpurchased_formatsに追加
        context['purchased_captures'] = []
        context['purchased_formats'] = []

        if self.request.user.pk:
            orders = Order.objects.filter(user=self.request.user, is_confirmed=True)
            for order in orders:
                order_items = json.loads(order.items)
                for order_item in order_items:
                    if order_item['name'] == item.name:
                        for format in order_item['formats']:
                            captures = Capture.objects.filter(item=item.pk, format=format)
                            if len(captures) == 1:
                                capture = captures[0]
                                if capture not in context['purchased_captures']:
                                    context['purchased_captures'].append(capture)
                                    context['purchased_formats'].append(format)

        return context
    
class CategoryListView(ListView):
    model = Item
    template_name = 'pages/list.html'
    paginate_by = 10
 
    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['pk'])
        return Item.objects.filter(is_published=True, category=self.category)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Category #{self.category.name}'
        return context
 
 
class TagListView(ListView):
    model = Item
    template_name = 'pages/list.html'
    paginate_by = 10
 
    def get_queryset(self):
        self.tag = Tag.objects.get(slug=self.kwargs['pk'])
        return Item.objects.filter(is_published=True, tags=self.tag)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Tag #{self.tag.name}"
        return context

base/views/legal_information_views.py
from django.views.generic import TemplateView

class LegalInformationView(TemplateView):
    template_name = 'pages/legal_information.html'

base/views/order_views.py
from django.views.generic import ListView, DetailView
from base.models import Order, Capture, Item, Format
import json
from django.contrib.auth.mixins import LoginRequiredMixin
 
 
class OrderIndexView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'pages/orders.html'
    # ordering = '-created_at'
 
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_confirmed=True).order_by('-created_at')
 
 
class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'pages/order.html'
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        # json to dict
        context["items"] = json.loads(obj.items)
        for item in context["items"]:
            item['captures'] = []
            for format in item['formats']:
                item['captures'].append( Capture.objects.filter(item=item['pk'], format=format).values()[0] )

        context["shipping"] = json.loads(obj.shipping)
        
        return context

templates/pages/about_us.html
{% extends 'base.html' %}

{% block main %}
<style>
    body {
        font-family: 'Arial', sans-serif;
    }
    .about-us-section {
        background-color: #f8f9fa;
        padding: 60px 0;
    }
    .about-us-header {
        text-align: center;
        margin-bottom: 40px;
        font-weight: bold;
        font-size: 2.5rem;
        color: #343a40;
    }
    .about-us-text {
        font-size: 1.125rem;
        line-height: 1.7;
        color: #495057;
    }
    .about-us-card {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        padding: 30px;
    }
    .subheading {
        font-size: 1.5rem;
        font-weight: bold;
        margin-top: 20px;
        color: #343a40;
    }
</style>
<div class="container about-us-section">
    <div class="row">
        <div class="col-lg-8 mx-auto about-us-card">
            <h2 class="about-us-header">ABOUT US</h2>
            
            <div>
                <p class="subheading">Who We Are</p>
                <p class="about-us-text">
                    Our company is based in Japan and specializes in capturing guitar amplifiers and other guitar gear. We provide versatile and high-quality capture technology that eliminates the need for physical equipment, catering to the diverse needs of musicians and creators.
                </p>
            </div>

            <div>
                <p class="subheading">Our Capture Technology</p>
                <p class="about-us-text">
                    Our captures cover all channels of guitar amplifiers, capturing preamp gain in whole-number units and, when necessary, allowing for adjustments in decimal units. This precise capture allows musicians to freely create their ideal sound.
                </p>
            </div>

            <div>
                <p class="subheading">Versatility Across Platforms</p>
                <p class="about-us-text">
                    Furthermore, we prioritize versatility and currently support various platforms such as 
                    <a href="https://www.ikmultimedia.com/products/tonex/" target="_blank" rel="noopener noreferrer">TONEX</a>, 
                    <a href="https://www.stltones.com/products/stl-tonehub-plugin" target="_blank" rel="noopener noreferrer">ToneHub Tracer</a>, and 
                    <a href="https://www.neuralampmodeler.com/users" target="_blank" rel="noopener noreferrer">Neural Amp Modeler</a>, 
                    providing an environment that accommodates a wide range of users.
                </p>
            </div>

            <div>
                <p class="subheading">Commitment to Sound Quality</p>
                <p class="about-us-text">
                    We are also dedicated to ensuring the highest sound quality by carefully selecting our equipment and sound capture environment. From audio interfaces and cables to the humidity of the recording space, we take meticulous care in creating an optimal environment to deliver the best sound.
                </p>
            </div>

            <div>
                <p class="subheading">Our Continuous Pursuit of Excellence</p>
                <p class="about-us-text">
                    Our technology enables more efficient music production and richer expressions, and we continuously strive to pursue the highest quality in all that we do.
                </p>
            </div>

        </div>
    </div>
</div>


{% endblock %}

templates/pages/account.html
{% extends 'base.html' %}
 
{% block main %}
 
<div class="container my-5">
  <div class="row">
    <div class="col-12 offset-md-4">
      <h1>Account</h1>
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Username</label>
            <input class="form-control" type="text" name="username" placeholder="name" value="{{user.username}}">
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Email</label>
            <input class="form-control" type="email" name="email" placeholder="Email" value="{{user.email}}" required>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Change Password</label>
            <input class="form-control" type="password" name="current_password" placeholder="Current Password">
            <input class="form-control" type="password" name="password" placeholder="New Password">
            <input class="form-control" type="password" name="password_confirm" placeholder="New Password Confirmation">
          </div>
        </div>

        <div class="form-check col-md-4">
          {% if user.newsletter %}
          <input class="form-check-input" type="checkbox" name="newsletter" id="id_newsletter" checked>
          {% else %}
          <input class="form-check-input" type="checkbox" name="newsletter" id="id_newsletter">
          {% endif %}
          <label class="form-check-label" for="id_newsletter">
            I'd like to receive emails about updates, offers, and news.
          </label>
        </div>

        <br>

        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>
 
{% endblock %}

templates/pages/cancel.html
{% extends 'base.html' %}

{% block main %}

<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1>Cancel</h1>
            <p>An Error Occured.<a href="/cart/">Cart</a></p>
        </div>
    </div>
</div>

{% endblock %}

templates/pages/cart.html
{% extends 'base.html' %}
 
{% block main %}
 
<div class="container ">
  <div class="row my-5">
    <div class="col-12">
      <h2>Cart</h2>
      {% if object_list|length != 0 %}
      <table class="table mb-5 text-right">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price(USD)</th>
            <th scope="col">Formats</th>
            <th scope="col">Sum</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>No.{{forloop.counter}}</td>
            <td>{{object.name}}</td>
            <td>{{object.price}}</td>
            <td>
              {% for format in object.purchase_formats %}
              {{format}}<br>
              {% endfor %}
            </td>
            <td>{{object.subtotal}}</td>
            <td><a href="/cart/remove/{{object.pk}}/" class="my-auto btn btn-danger btn-sm">Delete</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <p class="lead text-right">Subtotal - ${{total}}</p>
      <p class="lead text-right">Total - ${{tax_included_total}}(Tax Included)</p>
 
      <!-- Checkoutボタン -->
      <form action="/pay/checkout/" method="POST" class="text-right">
        {% csrf_token %}
        <button type="submit" class="btn btn-info">Checkout</button>
      </form>
 
      {% else %}
      <p class="">Nothing items in your cart.</p>
      {% endif %}
    </div>
  </div>

  <h2>Recommendations</h2>
  <div class="row mb-5">
    {% for object in POPULAR_ITEMS %}
    {% if forloop.counter < 4 %}
    <div class="col-12 col-lg-3 my-3">
      {% include 'snippets/item_box.html' %}
    </div>
    {% endif %}
    {% endfor %}
  </div>

</div>
 
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}

{% block main %}

{% include 'snippets/headline.html' %}
 
<div class="container px-5" style="max-width:100%">
  <h1 class="row my-5">Recent Capturing</h1>
  <div class="row my-5">
    {% for object in RECENT_ITEMS %}
    {% if forloop.counter < 4 %}
    <div class="col-12 col-lg-3 my-3">
      {% include 'snippets/item_box.html' %}
    </div>
    {% endif %}
    {% endfor %}
  </div>

    {% for dict in dict_list %}
    {% for key, list in dict.items %}
    <h1><a href="/categories/{{key.slug}}/" class="badge badge-pill badge-warning">{{key.name}}</a></h1>
    <div class="row my-5">
    {% for object in list %}
    <div class="col-12 col-lg-3 my-3">
      {% include 'snippets/item_box.html' %}
    </div>
    {% endfor %}
    </div>

    {% endfor %}
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/pages/item.html
{% extends 'base.html' %}
 
{% block main %}
<div class="container">
  <div class="row my-5">
    <div class="col-12 col-lg-6">
      <div class="bg-white border overflow-hidden">
        <img src="/{{ object.image }}" width="100%">
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="border p-3 text-left text-dark overflow-hidden">
        <h2 class="display-5">{{object.name}}</h2>
        <p class="lead">
          <a href="/categories/{{object.category.slug}}/"
            class="badge badge-pill badge-warning">{{object.category.name}}</a>
          {% for tag in object.tags.all %}
          <a href="/tags/{{tag.slug}}/" class="badge badge-pill badge-light">#{{tag}}</a>
          {% endfor %}
        </p>
        <p class="lead">${{object.price}}</p>
        <p class="lead">{{object.description | linebreaks}}</p>

        <iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" 
        src="{{object.soundcloud_src}}">
        </iframe>


        {% if purchased_formats %}
        <div class="lead">You have already puachased these formats</div>
        {% endif %}
        <ul>
          {% for purchased in purchased_captures %}
          <li><a href="/downloads/capture/{{purchased.id}}/">{{purchased.format}}</a> <i class="bi bi-file-zip"></i></li>
          {% endfor %}
        </ul>

        <form action="/cart/add/" method="POST" class="">
          {% csrf_token %}
          <input type="hidden" name="item_pk" value="{{object.pk}}">
          <p class="lead">
            Select Formats

            {% for format in object.formats.all %}

            {% if format.name not in purchased_formats %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="formats" value="{{format}}" id="{{format}}">
              <label class="form-check-label" for="{{format}}">
                {{ format }}
              </label>
            </div>
            {% endif %}

            {% endfor %}
          </p>
          <p>
            <button type="submit" class="btn btn-success">Add to cart</button>
          </p>
        </form>
      </div>
    </div>
  </div>

  <h2>Recommendations</h2>
  <div class="row mb-5">
    {% for object in RECENT_ITEMS %}
    {% if forloop.counter < 4 %}
    <div class="col-12 col-lg-3 my-3">
      {% include 'snippets/item_box.html' %}
    </div>
    {% endif %}
    {% endfor %}
  </div>

</div>
{% endblock %}

templates/pages/legal_information.html
{% extends 'base.html' %}

{% block main %}

<div class="container my-5">
    <h1 class="text-center mb-4">Specified Commercial Transactions Act Statement</h1>
    <div class="row">
        <div class="col-md-6">
            <h3>Seller Information</h3>
            <ul class="list-unstyled">
                <li><strong>Company Name:</strong> Tokyo DSP</li>
                <li><strong>Representative:</strong> Takumi Okabe</li>
                <li><strong>Address:</strong> 2-12-8-306, Sagamidai, Sagamihara-Minamiku, Kanagawa, 252-0321</li>
                <li><strong>Phone Number:</strong> +81-70-9001-0968</li>
                <li><strong>Email Address:</strong> tokyodsp2025@gmail.com</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h3>Price</h3>
            <p>The price of the products will be as indicated on each product page.<br>Additional costs such as shipping fees and handling fees will be displayed during the checkout process.</p>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <h3>Payment Methods</h3>
            <ul class="list-unstyled">
                <li>Credit Card with Stripe</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h3>Delivery Time</h3>
            <p>Once the purchase is complete, the product will be available for immediate download from the order page.</p>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <h3>Returns and Exchanges</h3>
            <p>Returns and exchanges are generally not accepted. However, we will accept returns or exchanges under the following conditions:<br>
            ・ If the product is defective<br>
            ・ If the product is different from what was ordered<br>
            Please contact us within 7 days of receiving the product if you wish to return or exchange it.</p>
        </div>
        <div class="col-md-6">
            <h3>Other Notes</h3>
            <p>If there are any restrictions on the sales area or special sales conditions, they will be indicated on the product page.<br>Please contact us for more details.</p>
        </div>
    </div>
</div>

{% endblock %}

templates/pages/list.html
{% extends 'base.html' %}
 
{% block main %}
 
<div class="row m-5">
  <div class="col-12 my-3">
    <h1>{{ title }}</h1>
  </div>
  {% for object in object_list %}
  <div class="col-12 col-lg-3 my-3">
    {% include 'snippets/item_box.html' %}
  </div>
  {% endfor %}
</div>
 
<div class="row m-5">
  <div class="col-12 my-3">
    {% include 'snippets/pagination.html' %}
  </div>
</div>
 
{% endblock %}

templates/pages/orders.html
{% extends 'base.html' %}
 
{% block main %}
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <h1>Orders</h1>
      <table class="table table-striped ">
        <thead>
          <tr>
            <th scope="col">No.</th>
            <th scope="col">Created at</th>
            <th scope="col">Tax included</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td><a href="/orders/{{object.pk}}/">{{object.pk}}</a></td>
            <td>{{object.created_at|date:"Y-m-d f"}}</td>
            <td>${{object.tax_included}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}